version: '3.0'

services:
    main:
      container_name: main
      build:
        context: .
      working_dir: ./
      restart: unless-stopped
      ports:
        - '3000:3000'
    volumes: 
      - .:/app
      - .:/app/node_modules